version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    volumes:
      - ./php:/var/www/html
    ports:
      - "8080:80"

  mariadb:
    image: mariadb:10.5  # Cambia la imagen a MariaDB
    container_name: mariadb_db  # Cambia el nombre del contenedor
    environment:
      MYSQL_ROOT_PASSWORD: alciribarren
      MYSQL_DATABASE: bdpresupuesto
      MYSQL_USER: presudev
      MYSQL_PASSWORD: presudev2024
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  tomcat:
    image: tomcat:9.0
    container_name: tomcat_app
    ports:
      - "8081:8080"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps

volumes:
  mysql_data:
